manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/Katona
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: split_battery_service
      import: app/west.yml
  self:
    path: config
